apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mvlgqlfse-go 
  janus-idp.io/tekton: mvlgqlfse-go
  backstage.io/kubernetes-id: mvlgqlfse-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mvlgqlfse-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml